using MediatR;

namespace Backbone.Modules.Devices.Application.Identities.Queries.ListAddressesOfIdentitiesWithDeletionProcessInStatusDeleting;

public class ListAddressesOfIdentitiesWithDeletionProcessInStatusDeletingQuery : IRequest<ListAddressesOfIdentitiesWithDeletionProcessInStatusDeletingResponse>;
