using OpenIddict.EntityFrameworkCore.Models;

namespace Backbone.Devices.Infrastructure.OpenIddict;
public class CustomOpenIddictEntityFrameworkCoreToken : OpenIddictEntityFrameworkCoreToken<string, CustomOpenIddictEntityFrameworkCoreApplication, CustomOpenIddictEntityFrameworkCoreAuthorization>
{
}

