using OpenIddict.EntityFrameworkCore.Models;

namespace Backbone.Devices.Infrastructure.OpenIddict;
public class CustomOpenIddictEntityFrameworkCoreAuthorization : OpenIddictEntityFrameworkCoreAuthorization<string, CustomOpenIddictEntityFrameworkCoreApplication, CustomOpenIddictEntityFrameworkCoreToken>
{
}
