version: 2
updates:
  ##### GitHub Actions #####
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-github-actions-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  ##### Pipeline scripts #####
  - package-ecosystem: "npm"
    directory: /.ci
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  ##### Admin UI Angular App #####
  - package-ecosystem: "npm"
    directory: "/AdminUi/src/AdminUi/ClientApp"
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  ##### Performance Tests #####
  - package-ecosystem: "npm"
    directory: /Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: /Modules/Files/test/Files.API.Tests.Performance.EndToEnd
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: /Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: /Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: /Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"
