version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-nuget-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "OpenIddict.*"
          - "AspNetCore.HealthChecks.NpgSql"
          - "Npgsql.EntityFrameworkCore.PostgreSQL"
          - "Microsoft.IdentityModel.Tokens"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-github-actions-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"
