version: 2
updates:
  ##### NuGet packages for Backbone.sln #####
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-nuget-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  ##### GitHub Actions #####
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-github-actions-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  ##### Pipeline scripts #####
  - package-ecosystem: "npm"
    directory: /.ci
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  ##### Admin UI Angular App #####
  - package-ecosystem: "npm"
    directory: "/AdminUi/src/AdminUi/ClientApp"
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
      - "daniel-almeida-konkconsulting"
    labels:
      - "dependencies"
