version: 2
updates:
  ##### NuGet packages for Backbone.sln #####
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-nuget-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  ##### GitHub Actions #####
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      update-github-actions-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"

  ##### Pipeline scripts #####
  - package-ecosystem: "npm"
    directory: /.ci
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"] # Ignore this until https://github.com/typescript-eslint/typescript-eslint/issues/8211 is fixed
    labels:
      - "dependencies"

  ##### Admin UI Angular App #####
  - package-ecosystem: "npm"
    directory: "/AdminApi/src/AdminApi/ClientApp"
    schedule:
      interval: "weekly"
    groups:
      update-npm-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
      - "daniel-almeida-konkconsulting"
    labels:
      - "dependencies"

  ##### Docker #####
  - package-ecosystem: "docker"
    directories:
      - "/AdminApi/src/AdminApi"
      - "/ConsumerApi"
      - "/DatabaseMigrator"
      - "/EventHandlerService/src/EventHandlerService"
      - "/Jobs/src/Job.IdentityDeletion"
      - "/Modules/Devices/src/Devices.AdminCli"
    schedule:
      interval: "weekly"
    groups:
      update-docker-dependencies:
        patterns:
          - "*"
    reviewers:
      - "tnotheis"
    labels:
      - "dependencies"
