FROM node:20

WORKDIR /app

EXPOSE 4200

COPY AdminUi/src/AdminUi/ClientApp/package*.json ./
COPY AdminUi/src/AdminUi/ClientApp/tsconfig.json ./
COPY AdminUi/src/AdminUi/ClientApp/tsconfig.app.json ./

RUN npm install

CMD ["npm", "start"]
