global:
  provider: "GoogleCloud"

  serviceAccount:
    name: "bucket-service-account"

  configuration:
    swaggerUi:
      tokenUrl: "https://bkb-nmshd-integration.nbpdev.de/connect/token"
    infrastructure:
      eventBus:
        vendor: RabbitMQ
        connectionInfo: "rabbitmq"
        rabbitMQUsername: "admin"
    modules:
      challenges:
        infrastructure:
          sqlDatabase:
            provider: "Postgres"
      devices:
        application:
        infrastructure:
          sqlDatabase:
            provider: "Postgres"
          pushNotifications:
            provider: "Dummy"
            azureNotificationHub:
              hubName: "a"
              connectionString: "a"
      files:
        infrastructure:
          sqlDatabase:
            provider: "Postgres"
          blobStorage:
            cloudProvider: "GoogleCloud"
            containerName: "bkt-nbp-test-nmshd-bkb-files-integration"
      messages:
        infrastructure:
          sqlDatabase:
            provider: "Postgres"
          blobStorage:
            cloudProvider: "GoogleCloud"
            containerName: "bkt-nbp-test-nmshd-bkb-messages-integration"
      relationships:
        infrastructure:
          sqlDatabase:
            provider: "Postgres"
          blobStorage:
            cloudProvider: "GoogleCloud"
            containerName: "bkt-nbp-test-nmshd-bkb-relationships-integration"
      synchronization:
        infrastructure:
          sqlDatabase:
            provider: "Postgres"
          blobStorage:
            cloudProvider: "GoogleCloud"
            containerName: "bkt-nbp-test-nmshd-bkb-synchronization-integration"
      tokens:
        infrastructure:
          sqlDatabase:
            provider: "Postgres"
          blobStorage:
            cloudProvider: "GoogleCloud"
            containerName: "bkt-nbp-test-nmshd-bkb-tokens-integration"

consumerapi:
  httpRoute:
    enabled: true
    parentRefName: "public-gateway"
    parentRefNamespace: "default"
    hostnames: ["bkb-nmshd-integration.nbpdev.de"]
  env:
    - name: authentication__jwtSigningCertificate
      valueFrom:
        secretKeyRef:
          name: "jwt-signing-certificate"
          key: "VALUE"
    - name: modules__challenges__infrastructure__sqlDatabase__connectionString
      valueFrom:
        secretKeyRef:
          name: "challenges-sql-connectionstring"
          key: "VALUE"
    - name: modules__Devices__infrastructure__sqlDatabase__connectionString
      valueFrom:
        secretKeyRef:
          name: "devices-sql-connectionstring"
          key: "VALUE"
    - name: modules__Files__infrastructure__sqlDatabase__connectionString
      valueFrom:
        secretKeyRef:
          name: "files-sql-connectionstring"
          key: "VALUE"
    - name: modules__Messages__infrastructure__sqlDatabase__connectionString
      valueFrom:
        secretKeyRef:
          name: "messages-sql-connectionstring"
          key: "VALUE"
    - name: modules__Relationships__infrastructure__sqlDatabase__connectionString
      valueFrom:
        secretKeyRef:
          name: "relationships-sql-connectionstring"
          key: "VALUE"
    - name: modules__Synchronization__infrastructure__sqlDatabase__connectionString
      valueFrom:
        secretKeyRef:
          name: "synchronization-sql-connectionstring"
          key: "VALUE"
    - name: modules__Tokens__infrastructure__sqlDatabase__connectionString
      valueFrom:
        secretKeyRef:
          name: "tokens-sql-connectionstring"
          key: "VALUE"

admincli:
  env:
    - name: Database__ConnectionString
      valueFrom:
        secretKeyRef:
          name: "devices-sql-connectionstring"
          key: "VALUE"

rabbitmq:
  create: true
