<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\BuildingBlocks\src\BuildingBlocks.API\BuildingBlocks.API.csproj" />
        <ProjectReference Include="..\..\..\..\BuildingBlocks\src\BuildingBlocks.Module\BuildingBlocks.Module.csproj" />
        <ProjectReference Include="..\..\..\Devices\src\Devices.Contracts\Devices.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Files\src\Files.Contracts\Files.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Messages\src\Messages.Contracts\Messages.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Relationships\src\Relationships.Contracts\Relationships.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Tokens\src\Tokens.Contracts\Tokens.Contracts.csproj" />
        <ProjectReference Include="..\Quotas.Contracts\Quotas.Contracts.csproj" />
        <ProjectReference Include="..\Quotas.Domain\Quotas.Domain.csproj" />
        <ProjectReference Include="..\Quotas.Abstractions\Quotas.Abstractions.csproj" />
        <ProjectReference Include="..\Quotas.Infrastructure.Database.Postgres\Quotas.Infrastructure.Database.Postgres.csproj" />
        <ProjectReference Include="..\Quotas.Infrastructure.Database.SqlServer\Quotas.Infrastructure.Database.SqlServer.csproj" />
        <ProjectReference Include="..\Quotas.Infrastructure\Quotas.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ReHackt.Extensions.Options.Validation" />
    </ItemGroup>

</Project>
