apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-for-databasemigrator
  labels: {{- include "global.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  appsettings.override.json: |-
    {{- mustToPrettyJson .Values.global.configuration | toString | nindent 4 }}
