// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace AdminUi.Infrastructure.CompiledModels.Postgres
{
    public partial class AdminUiDbContextModel
    {
        partial void Initialize()
        {
            var clientOverview = ClientOverviewEntityType.Create(this);
            var identityOverview = IdentityOverviewEntityType.Create(this);
            var tierOverview = TierOverviewEntityType.Create(this);

            ClientOverviewEntityType.CreateAnnotations(clientOverview);
            IdentityOverviewEntityType.CreateAnnotations(identityOverview);
            TierOverviewEntityType.CreateAnnotations(tierOverview);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "7.0.11");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
