apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
  labels: {{- include "global.labels" . | nindent 4 }}
data:
  appsettings.override.json: |-
    {{- mustToPrettyJson .Values.global.configuration | toString | nindent 4 }}
