// <auto-generated />
using Backbone.Modules.Messages.Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Backbone.Modules.Messages.Infrastructure.CompiledModels.SqlServer
{
    [DbContext(typeof(MessagesDbContext))]
    public partial class MessagesDbContextModel : RuntimeModel
    {
        static MessagesDbContextModel()
        {
            var model = new MessagesDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static MessagesDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
