// <auto-generated />
using System;
using Backbone.Modules.Announcements.Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backbone.Modules.Announcements.Infrastructure.Database.Postgres.Migrations
{
    [DbContext(typeof(AnnouncementsDbContext))]
    [Migration("20250110112331_AddingAnnouncementRecipient")]
    partial class AddingAnnouncementRecipient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Announcements")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backbone.BuildingBlocks.Domain.Events.DomainEvent", b =>
                {
                    b.Property<string>("DomainEventId")
                        .HasColumnType("text");

                    b.Property<string>("AnnouncementRecipientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DomainEventId");

                    b.HasIndex("AnnouncementRecipientId");

                    b.ToTable("DomainEvent", "Announcements");
                });

            modelBuilder.Entity("Backbone.Modules.Announcements.Domain.Entities.Announcement", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character(20)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Announcements", "Announcements");
                });

            modelBuilder.Entity("Backbone.Modules.Announcements.Domain.Entities.AnnouncementRecipient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnnouncementId1")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character(20)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId1");

                    b.ToTable("AnnouncementRecipients", "Announcements");
                });

            modelBuilder.Entity("Backbone.Modules.Announcements.Domain.Entities.AnnouncementText", b =>
                {
                    b.Property<string>("AnnouncementId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character(20)")
                        .IsFixedLength();

                    b.Property<string>("Language")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnouncementId", "Language");

                    b.ToTable("AnnouncementText", "Announcements");
                });

            modelBuilder.Entity("Backbone.BuildingBlocks.Domain.Events.DomainEvent", b =>
                {
                    b.HasOne("Backbone.Modules.Announcements.Domain.Entities.AnnouncementRecipient", null)
                        .WithMany("DomainEvents")
                        .HasForeignKey("AnnouncementRecipientId");
                });

            modelBuilder.Entity("Backbone.Modules.Announcements.Domain.Entities.AnnouncementRecipient", b =>
                {
                    b.HasOne("Backbone.Modules.Announcements.Domain.Entities.Announcement", null)
                        .WithMany("Recipients")
                        .HasForeignKey("AnnouncementId1");
                });

            modelBuilder.Entity("Backbone.Modules.Announcements.Domain.Entities.AnnouncementText", b =>
                {
                    b.HasOne("Backbone.Modules.Announcements.Domain.Entities.Announcement", null)
                        .WithMany("Texts")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backbone.Modules.Announcements.Domain.Entities.Announcement", b =>
                {
                    b.Navigation("Recipients");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("Backbone.Modules.Announcements.Domain.Entities.AnnouncementRecipient", b =>
                {
                    b.Navigation("DomainEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
