using MediatR;

namespace Backbone.Modules.Devices.Module.Features.Identities.ListAddressesOfIdentitiesWithDeletionProcessInStatusDeleting;

public class ListAddressesOfIdentitiesWithDeletionProcessInStatusDeletingQuery : IRequest<ListAddressesOfIdentitiesWithDeletionProcessInStatusDeletingResponse>;
