class Language {
  final String isoCode;
  final String name;

  const Language(this.isoCode, this.name);
}

class Languages {
  static const List<Language> languages = [
    Language('aa', 'Afar'),
    Language('ab', 'Abkhaz'),
    Language('ae', 'Avestan'),
    Language('af', 'Afrikaans'),
    Language('ak', 'Akan'),
    Language('am', 'Amharic'),
    Language('an', 'Aragonese'),
    Language('ar', 'Arabic'),
    Language('as', 'Assamese'),
    Language('av', 'Avaric'),
    Language('ay', 'Aymara'),
    Language('az', 'Azerbaijani'),
    Language('ba', 'Bashkir'),
    Language('be', 'Belarusian'),
    Language('bg', 'Bulgarian'),
    Language('bi', 'Bislama'),
    Language('bm', 'Bambara'),
    Language('bn', 'Bengali'),
    Language('bo', 'Tibetan'),
    Language('br', 'Breton'),
    Language('bs', 'Bosnian'),
    Language('ca', 'Catalan'),
    Language('ce', 'Chechen'),
    Language('ch', 'Chamorro'),
    Language('co', 'Corsican'),
    Language('cr', 'Cree'),
    Language('cs', 'Czech'),
    Language('cu', 'Old Church Slavonic'),
    Language('cv', 'Chuvash'),
    Language('cy', 'Welsh'),
    Language('da', 'Danish'),
    Language('de', 'German'),
    Language('dv', 'Divehi'),
    Language('dz', 'Dzongkha'),
    Language('ee', 'Ewe'),
    Language('el', 'Greek'),
    Language('en', 'English'),
    Language('eo', 'Esperanto'),
    Language('es', 'Spanish'),
    Language('et', 'Estonian'),
    Language('eu', 'Basque'),
    Language('fa', 'Persian'),
    Language('ff', 'Fula'),
    Language('fi', 'Finnish'),
    Language('fj', 'Fijian'),
    Language('fo', 'Faroese'),
    Language('fr', 'French'),
    Language('fy', 'Western Frisian'),
    Language('ga', 'Irish'),
    Language('gd', 'Scottish Gaelic'),
    Language('gl', 'Galician'),
    Language('gn', 'Guaraní'),
    Language('gu', 'Gujarati'),
    Language('gv', 'Manx'),
    Language('ha', 'Hausa'),
    Language('he', 'Hebrew'),
    Language('hi', 'Hindi'),
    Language('ho', 'Hiri Motu'),
    Language('hr', 'Croatian'),
    Language('ht', 'Haitian'),
    Language('hu', 'Hungarian'),
    Language('hy', 'Armenian'),
    Language('hz', 'Herero'),
    Language('ia', 'Interlingua'),
    Language('id', 'Indonesian'),
    Language('ie', 'Interlingue'),
    Language('ig', 'Igbo'),
    Language('ii', 'Nuosu'),
    Language('ik', 'Inupiaq'),
    Language('io', 'Ido'),
    Language('is', 'Icelandic'),
    Language('it', 'Italian'),
    Language('iu', 'Inuktitut'),
    Language('ja', 'Japanese'),
    Language('jv', 'Javanese'),
    Language('ka', 'Georgian'),
    Language('kg', 'Kongo'),
    Language('ki', 'Kikuyu'),
    Language('kj', 'Kwanyama'),
    Language('kk', 'Kazakh'),
    Language('kl', 'Kalaallisut'),
    Language('km', 'Khmer'),
    Language('kn', 'Kannada'),
    Language('ko', 'Korean'),
    Language('kr', 'Kanuri'),
    Language('ks', 'Kashmiri'),
    Language('ku', 'Kurdish'),
    Language('kv', 'Komi'),
    Language('kw', 'Cornish'),
    Language('ky', 'Kyrgyz'),
    Language('la', 'Latin'),
    Language('lb', 'Luxembourgish'),
    Language('lg', 'Ganda'),
    Language('li', 'Limburgish'),
    Language('ln', 'Lingala'),
    Language('lo', 'Lao'),
    Language('lt', 'Lithuanian'),
    Language('lu', 'Luba-Katanga'),
    Language('lv', 'Latvian'),
    Language('mg', 'Malagasy'),
    Language('mh', 'Marshallese'),
    Language('mi', 'Māori'),
    Language('mk', 'Macedonian'),
    Language('ml', 'Malayalam'),
    Language('mn', 'Mongolian'),
    Language('mr', 'Marathi'),
    Language('ms', 'Malay'),
    Language('mt', 'Maltese'),
    Language('my', 'Burmese'),
    Language('na', 'Nauru'),
    Language('nb', 'Norwegian Bokmål'),
    Language('nd', 'Northern Ndebele'),
    Language('ne', 'Nepali'),
    Language('ng', 'Ndonga'),
    Language('nl', 'Dutch'),
    Language('nn', 'Norwegian Nynorsk'),
    Language('no', 'Norwegian'),
    Language('nr', 'Southern Ndebele'),
    Language('nv', 'Navajo'),
    Language('ny', 'Chichewa'),
    Language('oc', 'Occitan'),
    Language('oj', 'Ojibwe'),
    Language('om', 'Oromo'),
    Language('or', 'Oriya'),
    Language('os', 'Ossetian'),
    Language('pa', 'Panjabi'),
    Language('pi', 'Pāli'),
    Language('pl', 'Polish'),
    Language('ps', 'Pashto'),
    Language('pt', 'Portuguese'),
    Language('qu', 'Quechua'),
    Language('rm', 'Romansh'),
    Language('rn', 'Kirundi'),
    Language('ro', 'Romanian'),
    Language('ru', 'Russian'),
    Language('rw', 'Kinyarwanda'),
    Language('sa', 'Sanskrit'),
    Language('sc', 'Sardinian'),
    Language('sd', 'Sindhi'),
    Language('se', 'Northern Sami'),
    Language('sg', 'Sango'),
    Language('si', 'Sinhala'),
    Language('sk', 'Slovak'),
    Language('sl', 'Slovenian'),
    Language('sm', 'Samoan'),
    Language('sn', 'Shona'),
    Language('so', 'Somali'),
    Language('sq', 'Albanian'),
    Language('sr', 'Serbian'),
    Language('ss', 'Swati'),
    Language('st', 'Southern Sotho'),
    Language('su', 'Sundanese'),
    Language('sv', 'Swedish'),
    Language('sw', 'Swahili'),
    Language('ta', 'Tamil'),
    Language('te', 'Telugu'),
    Language('tg', 'Tajik'),
    Language('th', 'Thai'),
    Language('ti', 'Tigrinya'),
    Language('tk', 'Turkmen'),
    Language('tl', 'Tagalog'),
    Language('tn', 'Tswana'),
    Language('to', 'Tonga'),
    Language('tr', 'Turkish'),
    Language('ts', 'Tsonga'),
    Language('tt', 'Tatar'),
    Language('tw', 'Twi'),
    Language('ty', 'Tahitian'),
    Language('ug', 'Uyghur'),
    Language('uk', 'Ukrainian'),
    Language('ur', 'Urdu'),
    Language('uz', 'Uzbek'),
    Language('ve', 'Venda'),
    Language('vi', 'Vietnamese'),
    Language('vo', 'Volapük'),
    Language('wa', 'Walloon'),
    Language('wo', 'Wolof'),
    Language('xh', 'Xhosa'),
    Language('yi', 'Yiddish'),
    Language('yo', 'Yoruba'),
    Language('za', 'Zhuang'),
    Language('zh', 'Chinese'),
    Language('zu', 'Zulu'),
  ];
}
