// <auto-generated />
using Backbone.Modules.Relationships.Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Backbone.Modules.Relationships.Infrastructure.CompiledModels.SqlServer
{
    [DbContext(typeof(RelationshipsDbContext))]
    public partial class RelationshipsDbContextModel : RuntimeModel
    {
        static RelationshipsDbContextModel()
        {
            var model = new RelationshipsDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static RelationshipsDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
