// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Backbone.Modules.Relationships.Infrastructure.CompiledModels.SqlServer
{
    public partial class RelationshipsDbContextModel
    {
        partial void Initialize()
        {
            var relationship = RelationshipEntityType.Create(this);
            var relationshipChange = RelationshipChangeEntityType.Create(this);
            var relationshipChangeRequest = RelationshipChangeRequestEntityType.Create(this);
            var relationshipChangeResponse = RelationshipChangeResponseEntityType.Create(this);
            var relationshipTemplate = RelationshipTemplateEntityType.Create(this);
            var relationshipTemplateAllocation = RelationshipTemplateAllocationEntityType.Create(this);
            var relationshipCreationChange = RelationshipCreationChangeEntityType.Create(this, relationshipChange);
            var relationshipTerminationChange = RelationshipTerminationChangeEntityType.Create(this, relationshipChange);

            RelationshipEntityType.CreateForeignKey1(relationship, relationshipTemplate);
            RelationshipChangeEntityType.CreateForeignKey1(relationshipChange, relationship);
            RelationshipChangeRequestEntityType.CreateForeignKey1(relationshipChangeRequest, relationshipChange);
            RelationshipChangeResponseEntityType.CreateForeignKey1(relationshipChangeResponse, relationshipChange);
            RelationshipTemplateAllocationEntityType.CreateForeignKey1(relationshipTemplateAllocation, relationshipTemplate);

            RelationshipEntityType.CreateAnnotations(relationship);
            RelationshipChangeEntityType.CreateAnnotations(relationshipChange);
            RelationshipChangeRequestEntityType.CreateAnnotations(relationshipChangeRequest);
            RelationshipChangeResponseEntityType.CreateAnnotations(relationshipChangeResponse);
            RelationshipTemplateEntityType.CreateAnnotations(relationshipTemplate);
            RelationshipTemplateAllocationEntityType.CreateAnnotations(relationshipTemplateAllocation);
            RelationshipCreationChangeEntityType.CreateAnnotations(relationshipCreationChange);
            RelationshipTerminationChangeEntityType.CreateAnnotations(relationshipTerminationChange);

            AddAnnotation("ProductVersion", "7.0.13");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
