{{- if .Values.consumerapi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "global.name" . }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ include "global.name" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{ .Values.consumerapi.ingress.certName }}
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
spec:
  rules:
    - host: {{ .Values.consumerapi.ingress.host }}
      http:
        paths:
          - path: "/*"
            pathType: Prefix
            backend:
              service:
                name: {{ include "global.name" . }}
                port:
                  number: 8080   
{{- end }}
