# Build stage
FROM node:18-alpine as build-stage
EXPOSE 4200

WORKDIR /app

# all configuration files are json
COPY package*.json /app/
COPY angular.json /app/
COPY tsconfig*.json /app/
RUN npm install
RUN npm install -g @angular/cli
ENV NODE_OPTIONS=--max-old-space-size=8192
