# Build stage
FROM node:18.16-alpine as build-stage
EXPOSE 4200

WORKDIR /app

# all configuration files are json
COPY package*.json /app/
COPY angular.json /app/
COPY tsconfig*.json /app/
RUN npm install
RUN npm install -g @angular/cli
CMD ng serve --host 0.0.0.0 --poll 1000
