<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GitHubActionsTestLogger" />
        <PackageReference Include="MediatR" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BuildingBlocks\src\BuildingBlocks.SDK\BuildingBlocks.SDK.csproj" />
        <ProjectReference Include="..\BuildingBlocks\src\UnitTestTools\UnitTestTools.csproj" />
        <ProjectReference Include="..\BuildingBlocks\test\BuildingBlocks.Application.Tests\BuildingBlocks.Application.Tests.csproj" />
        <ProjectReference Include="..\BuildingBlocks\test\BuildingBlocks.Infrastructure.Tests\BuildingBlocks.Infrastructure.Tests.csproj" />
        <ProjectReference Include="..\BuildingBlocks\test\Crypto.Tests\Crypto.Tests.csproj" />
        <ProjectReference Include="..\BuildingBlocks\test\DevelopmentKit.Identity.Tests\DevelopmentKit.Identity.Tests.csproj" />
        <ProjectReference Include="..\BuildingBlocks\test\Tooling.Tests\Tooling.Tests.csproj" />
        <ProjectReference Include="..\Applications\EventHandlerService\test\EventHandlerService.Tests\EventHandlerService.Tests.csproj" />
        <ProjectReference Include="..\Applications\IdentityDeletionJobs\test\Job.IdentityDeletion.Tests\Job.IdentityDeletion.Tests.csproj" />
        <ProjectReference Include="..\Modules\Announcements\test\Announcements.Module.Tests\Announcements.Module.Tests.csproj" />
        <ProjectReference Include="..\Modules\Announcements\src\Announcements.Abstractions\Announcements.Abstractions.csproj" />
        <ProjectReference Include="..\Modules\Announcements\src\Announcements.Contracts\Announcements.Contracts.csproj" />
        <ProjectReference Include="..\Modules\Announcements\test\Announcements.Domain.Tests\Announcements.Domain.Tests.csproj" />
        <ProjectReference Include="..\Modules\Challenges\test\Challenges.Module.Tests\Challenges.Module.Tests.csproj" />
        <ProjectReference Include="..\Modules\Challenges\src\Challenges.Abstractions\Challenges.Abstractions.csproj" />
        <ProjectReference Include="..\Modules\Devices\test\Devices.Application.Tests\Devices.Application.Tests.csproj" />
        <ProjectReference Include="..\Modules\Devices\src\Devices.Contracts\Devices.Contracts.csproj" />
        <ProjectReference Include="..\Modules\Devices\test\Devices.Domain.Tests\Devices.Domain.Tests.csproj" />
        <ProjectReference Include="..\Modules\Devices\test\Devices.Infrastructure.Tests\Devices.Infrastructure.Tests.csproj" />
        <ProjectReference Include="..\Modules\Files\test\Files.Application.Tests\Files.Application.Tests.csproj" />
        <ProjectReference Include="..\Modules\Files\src\Files.Contracts\Files.Contracts.csproj" />
        <ProjectReference Include="..\Modules\Files\test\Files.Domain.Tests\Files.Domain.Tests.csproj" />
        <ProjectReference Include="..\Modules\Files\test\Files.Infrastructure.Tests\Files.Infrastructure.Tests.csproj" />
        <ProjectReference Include="..\Modules\Messages\src\Messages.Common\Messages.Common.csproj" />
        <ProjectReference Include="..\Modules\Messages\src\Messages.Contracts\Messages.Contracts.csproj" />
        <ProjectReference Include="..\Modules\Messages\src\Messages.Abstractions\Messages.Abstractions.csproj" />
        <ProjectReference Include="..\Modules\Messages\src\Messages.Infrastructure\Messages.Infrastructure.csproj" />
        <ProjectReference Include="..\Modules\Messages\src\Messages.Module\Messages.Module.csproj" />
        <ProjectReference Include="..\Modules\Messages\test\Messages.Module.Tests\Messages.Module.Tests.csproj" />
        <ProjectReference Include="..\Modules\Messages\test\Messages.Domain.Tests\Messages.Domain.Tests.csproj" />
        <ProjectReference Include="..\Modules\Quotas\test\Quotas.Application.Tests\Quotas.Application.Tests.csproj" />
        <ProjectReference Include="..\Modules\Quotas\src\Quotas.Contracts\Quotas.Contracts.csproj" />
        <ProjectReference Include="..\Modules\Quotas\test\Quotas.Domain.Tests\Quotas.Domain.Tests.csproj" />
        <ProjectReference Include="..\Modules\Quotas\test\Quotas.Infrastructure.Tests\Quotas.Infrastructure.Tests.csproj" />
        <ProjectReference Include="..\Modules\Synchronization\test\Synchronization.Application.Tests\Synchronization.Application.Tests.csproj" />
        <ProjectReference Include="..\Modules\Relationships\src\Relationships.Contracts\Relationships.Contracts.csproj" />
        <ProjectReference Include="..\Modules\Synchronization\src\Synchronization.Contracts\Synchronization.Contracts.csproj" />
        <ProjectReference Include="..\Modules\Synchronization\test\Synchronization.Domain.Tests\Synchronization.Domain.Tests.csproj" />
        <ProjectReference Include="..\Modules\Tags\src\Tags.Abstractions\Tags.Abstractions.csproj" />
        <ProjectReference Include="..\Modules\Tags\src\Tags.Domain\Tags.Domain.csproj" />
        <ProjectReference Include="..\Modules\Tags\src\Tags.Infrastructure\Tags.Infrastructure.csproj" />
        <ProjectReference Include="..\Modules\Tags\src\Tags.Module\Tags.Module.csproj" />
        <ProjectReference Include="..\Applications\ConsumerApi\src\ConsumerApi.csproj" />
        <ProjectReference Include="..\Modules\Tokens\src\Tokens.Abstractions\Tokens.Abstractions.csproj" />
        <ProjectReference Include="..\Modules\Tokens\test\Tokens.Module.Tests\Tokens.Module.Tests.csproj" />
        <ProjectReference Include="..\Modules\Tokens\src\Tokens.Contracts\Tokens.Contracts.csproj" />
        <ProjectReference Include="..\Modules\Tokens\test\Tokens.Domain.Tests\Tokens.Domain.Tests.csproj" />
    </ItemGroup>
</Project>
