services:
  ### infrastructure ###

  database:
    container_name: bkb-postgres-test
    hostname: postgres
    image: postgres:17.5@sha256:4d89c904835259bc58876520e56267ca07a4ebd6a027f7814bbbf91b50d685be
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=enmeshed
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ### seeds ###

  seed-database:
    volumes:
      - ../scripts/sql/postgres:/app/sql-scripts
    image: postgres:17.5@sha256:4d89c904835259bc58876520e56267ca07a4ebd6a027f7814bbbf91b50d685be
    environment:
      - PGPASSWORD=Passw0rd
    command: psql -h postgres -U postgres -d enmeshed -f /app/sql-scripts/setup.sql

  admin-cli:
    volumes:
      - ./appsettings.override.postgres.docker.json:/app/appsettings.override.json
    environment:
      Database__Provider: Postgres
      Database__ConnectionString: "Server=postgres;Database=enmeshed;User Id=devices;Password=Passw0rd;Port=5432"

  database-migrator:
    environment:
      Infrastructure__SqlDatabase__Provider: Postgres
      Infrastructure__SqlDatabase__ConnectionString: "Server=postgres;Database=enmeshed;User Id=postgres;Password=Passw0rd;Port=5432"

configs:
  Config:
    file: appsettings.override.postgres.docker.json

networks:
  default:
    name: backbone
