services:
  consumer-api:
    container_name: consumer-api-test
    hostname: consumer-api
    image: ghcr.io/nmshd/backbone-consumer-api:0.0.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    depends_on:
      database-migrator:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
      azure-storage-emulator:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  admin-ui:
    container_name: admin-ui-test
    hostname: admin-ui
    image: ghcr.io/nmshd/backbone-admin-ui:0.0.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5173:8080"
    depends_on:
      database-migrator:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  event-handler-service:
    container_name: event-handler-service-test
    image: ghcr.io/nmshd/backbone-event-handler:0.0.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      database-migrator:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  sse-server:
    container_name: sse-server-test
    image: ghcr.io/nmshd/backbone-sse-server:0.0.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      database-migrator:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json

  database-migrator:
    container_name: database-migrator-test
    image: ghcr.io/nmshd/backbone-database-migrator:0.0.1
    depends_on:
      seed-database:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    configs:
      - source: Config
        target: app/appsettings.override.json

  ### infrastructure ###

  azure-storage-emulator:
    container_name: azure-storage-emulator-test
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0@sha256:0a47e12e3693483cef5c71f35468b91d751611f172d2f97414e9c69113b106d9
    command: azurite -d /data/debug.log -l /data --blobHost "0.0.0.0" --queueHost "0.0.0.0"
    ports:
      - "10000:10000"

  rabbitmq:
    container_name: bkb-rabbitmq-test
    hostname: rabbitmq
    image: rabbitmq:4.1.0-management-alpine@sha256:81d71309efa2d589b8a992d08507d61abed4dfe13672c740fd4cc1c8e388bf32
    ports:
      - "5672:5672"

  ### seeds ###

  seed-database:
    depends_on:
      database:
        condition: service_healthy

  admin-cli:
    container_name: admin-cli-test
    image: ghcr.io/nmshd/backbone-admin-cli:0.0.1
    depends_on:
      consumer-api:
        condition: service_healthy
    command: backbone client create --clientId test --clientSecret test --defaultTier Basic

networks:
  default:
    name: backbone
