services:
  admin-ui:
    container_name: admin-ui-test
    hostname: admin-ui
    image: admin-ui:0.0.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5173:8080"
    depends_on:
      database-migrator:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    configs:
      - source: Config
        target: app/appsettings.override.json
