apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "global.name" . }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ include "global.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "global.name" . }}
  template:
    metadata:
      {{- with .Values.eventhandler.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "global.name" . }}
    spec:
      {{- with .Values.eventhandler.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.eventhandler.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.eventhandler.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: settings-override
          configMap:
            name: configuration
      containers:
        - name: {{ include "global.name" . }}
          {{- with .Values.eventhandler.securityContext }}
          securityContext:
            {{- toYaml .Values.eventhandler.securityContext | nindent 8 }}
          {{- end }}
          resources:
            {{- toYaml .Values.eventhandler.resources | nindent 12 }}
          image: "{{ .Values.eventhandler.image.repository }}:{{- default .Chart.AppVersion .Values.eventhandler.image.tagOverride }}"
          imagePullPolicy: {{ .Values.eventhandler.image.pullPolicy }}
          volumeMounts:
            - name: settings-override
              mountPath: /app/appsettings.override.json
              subPath: appsettings.override.json
              readOnly: true
          env:
            {{- if .Values.global.useBuiltInEventbus }}
            - name: infrastructure__eventBus__vendor
              value: RabbitMQ
            - name: infrastructure__eventBus__connectionInfo
              value: "rabbitmq"
            - name: infrastructure__eventBus__rabbitMQUsername
              value: "admin"
            - name: infrastructure__eventBus__rabbitMQPassword
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-password
                  key: "VALUE" 
            {{- end }}
            {{- with .Values.eventhandler.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.eventhandler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventhandler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventhandler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
