version: "3.3"
services:

  test-admin-ui:
    environment:
      - Modules__Devices__Infrastructure__SqlDatabase__ConnectionString=Server=ms-sql-server;Database=enmeshed;User Id=devices;Password=Passw0rd;TrustServerCertificate=True
      - Modules__Quotas__Infrastructure__SqlDatabase__ConnectionString=Server=ms-sql-server;Database=enmeshed;User Id=quotas;Password=Passw0rd;TrustServerCertificate=True
      - Infrastructure__SqlDatabase__ConnectionString=Server=ms-sql-server;Database=enmeshed;User Id=adminUi;Password=Passw0rd;TrustServerCertificate=True

  ### infrastructure ###

  test-database:
    container_name: bkb-mssql_server
    hostname: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes:
      - mssql-server-volume:/var/opt/mssql
    ports:
      - 1433:1433

  ### seeds ###

  test-seed-database:
    image: mcr.microsoft.com/mssql-tools
    volumes:
      - ../setup-db:/app/setup-db
    command: >
      bash -c " sleep 20 && /opt/mssql-tools/bin/sqlcmd -S ms-sql-server -U SA -P Passw0rd -q \"DROP DATABASE IF EXISTS enmeshed\" && /opt/mssql-tools/bin/sqlcmd -S ms-sql-server -U SA -P Passw0rd -q \"CREATE DATABASE enmeshed\" && sleep 1 && /opt/mssql-tools/bin/sqlcmd -S ms-sql-server -U SA -P Passw0rd -d enmeshed -i app/setup-db/setup-sqlserver.sql "
    depends_on:
      - test-database

  test-seed-client:
    command: >
      ./backbone client create -p SqlServer -c "Server=ms-sql-server;Database=enmeshed;User Id=devices;Password=Passw0rd;TrustServerCertificate=True" --clientId test --clientSecret test

configs:
  AdminUiOverrideConfig:
    file: ../AdminUi/src/AdminUi/appsettings.override.json
  ConsumerApiOverrideConfig:
    file: ../ConsumerApi/appsettings.override.json

networks:
  default:
    name: backbone

volumes:
  mssql-server-volume:
  
