services:
  ### infrastructure ###

  azure-storage-emulator:
    container_name: azure-storage-emulator
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37
    command: azurite-blob -l /data --blobHost "0.0.0.0" --skipApiVersionCheck
    ports:
      - "10000:10000"
    volumes:
      - azure-storage-emulator-volume:/data

  ms-sql-server:
    container_name: bkb-mssql_server
    hostname: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:d975fb1ea4c25c95309d7813b9f9133cde880fda16da24ab1379e277a9b2395b
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes:
      - mssql-server-volume:/var/opt/mssql
    ports:
      - 1433:1433

  postgres:
    container_name: bkb-postgres
    hostname: postgres
    image: postgres:18.3@sha256:7e32e9833a6fb1c92c32552794cb6ed569d51b445a54907d35fc112ef39684db
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-volume:/var/lib/postgresql
    ports:
      - 5432:5432

  rabbitmq:
    container_name: bkb-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.3.1-management-alpine@sha256:0c1330bfbaa544292d132eabe8f07bce4ec6f4817c0ca95bec0f2ba87483913f
    ports:
      - "5672:5672"
      - "15672:15672" # mgmt plugin, "guest/guest"
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq # default data dir

  seq:
    image: datalust/seq:2025.2@sha256:868a12e93ec0b8c993767a7dd4cd6c8ebc441511c79e4cfac66c911f62d4db65
    container_name: seq
    ports:
      - "8085:80"
      - "5341:5341"
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    restart: unless-stopped

networks:
  default:
    name: backbone

volumes:
  rabbitmq-volume:
  mssql-server-volume:
    external: true
  postgres-volume:
    external: true
  azure-storage-emulator-volume:
    external: true
  seq-data:
