version: "3.3"
services:
  test-consumer-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80

      - Modules__Files__Infrastructure__BlobStorage__CloudProvider=Azure
      - Modules__Files__Infrastructure__BlobStorage__ConnectionInfo=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - Modules__Files__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=files;Password=Passw0rd;Port=5432
      - Modules__Files__Infrastructure__SqlDatabase__Provider=Postgres

      - Modules__Messages__Infrastructure__BlobStorage__CloudProvider=Azure
      - Modules__Messages__Infrastructure__BlobStorage__ConnectionInfo=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - Modules__Messages__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=messages;Password=Passw0rd;Port=5432
      - Modules__Messages__Infrastructure__SqlDatabase__Provider=Postgres

      - Modules__Relationships__Infrastructure__BlobStorage__CloudProvider=Azure
      - Modules__Relationships__Infrastructure__BlobStorage__ConnectionInfo=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - Modules__Relationships__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=relationships;Password=Passw0rd;Port=5432
      - Modules__Relationships__Infrastructure__SqlDatabase__Provider=Postgres

      - Modules__Synchronization__Infrastructure__BlobStorage__CloudProvider=Azure
      - Modules__Synchronization__Infrastructure__BlobStorage__ConnectionInfo=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - Modules__Synchronization__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=synchronization;Password=Passw0rd;Port=5432
      - Modules__Synchronization__Infrastructure__SqlDatabase__Provider=Postgres

      - Modules__Tokens__Infrastructure__BlobStorage__CloudProvider=Azure
      - Modules__Tokens__Infrastructure__BlobStorage__ConnectionInfo=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - Modules__Tokens__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=tokens;Password=Passw0rd;Port=5432
      - Modules__Tokens__Infrastructure__SqlDatabase__Provider=Postgres

      - Modules__Devices__Infrastructure__SqlDatabase__Provider=Postgres
      - Modules__Devices__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=devices;Password=Passw0rd;Port=5432

      - Modules__Challenges__Infrastructure__SqlDatabase__Provider=Postgres
      - Modules__Challenges__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=challenges;Password=Passw0rd;Port=5432

      - Modules__Quotas__Infrastructure__SqlDatabase__Provider=Postgres
      - Modules__Quotas__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=quotas;Password=Passw0rd;Port=5432

  test-admin-ui:
    depends_on:
      test-seed-postgresql-2:
          condition: service_completed_successfully

    environment:
      - Modules__Devices__Infrastructure__SqlDatabase__Provider=Postgres
      - Modules__Devices__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=devices;Password=Passw0rd;Port=5432
      
      - Modules__Quotas__Infrastructure__SqlDatabase__Provider=Postgres
      - Modules__Quotas__Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=quotas;Password=Passw0rd;Port=5432
      
      - Infrastructure__SqlDatabase__Provider=Postgres
      - Infrastructure__SqlDatabase__ConnectionString=Server=postgresql;Database=enmeshed;User Id=adminUi;Password=Passw0rd;Port=5432
      
      - Infrastructure__EventBus__ConnectionInfo=rabbitmq

  ### infrastructure ###

  test-database:
    container_name: bkb-postgres
    hostname: postgresql
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=enmeshed
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ### seeds ###

  test-seed-client:
    command: >
      ./backbone client create -p Postgres -c "Server=postgresql;Database=enmeshed;User Id=devices;Password=Passw0rd;Port=5432" --clientId test --clientSecret test

  test-seed-database:
    container_name: seed-postgres
    image: postgres
    environment:
      - PGPASSWORD=Passw0rd
    command: >
      psql -h postgresql -U postgres -d enmeshed -f seed.sql
    configs:
      - source: DockerEntrypointInitdb
        target: seed.sql
    depends_on:
      test-database:
        condition: service_healthy

  test-seed-database-2:
    container_name: seed-postgres-2
    image: postgres
    environment:
      - PGPASSWORD=Passw0rd
    configs:
      - source: DockerEntrypointInitdb
        target: seed.sql
    command: >
      psql -h postgresql -U postgres enmeshed -f seed.sql
    depends_on:
      test-consumer-api:
        condition: service_healthy

configs:
  DockerEntrypointInitdb:
    file: ../setup-db/setup-postgres.sql

networks:
  default:
    name: backbone

volumes:
  postgresql-volume:
