{{- if .Values.consumerapi.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.consumerapi.name }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.consumerapi.httpRoute.parentRefName }}
      namespace: {{ .Values.consumerapi.httpRoute.parentRefNamespace }}
      sectionName: {{ .Values.consumerapi.httpRoute.parentRefSectionName }}
  hostnames:
  {{- if .Values.consumerapi.httpRoute.hostnamesOverride }}
    {{- toYaml .Values.consumerapi.httpRoute.hostnamesOverride | nindent 4 }}
  {{- else }}
    - {{ .Values.global.defaultHostname }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
    - matches:
        - path:
            type: Exact
            value: connect/token
      backendRefs:
        - name: {{ .Values.consumerapi.name }}
          port: 8080
{{- end }}
