{{- if .Values.consumerapi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.consumerapi.name }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ .Values.consumerapi.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.consumerapi.ingress.class }}
{{ toYaml .Values.consumerapi.ingress.annotations | indent 4 }}
spec:
  rules:
    - host: {{ .Values.consumerapi.ingress.hostnameOverride | default .Values.global.defaultHostname }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.consumerapi.name }}
                port:
                  number: 8080
  {{- if .Values.consumerapi.ingress.tls.enabled }}
  tls: 
    - hosts:
        - {{ .Values.consumerapi.ingress.hostnameOverride | default .Values.global.defaultHostname }}
      secretName: {{ .Values.consumerapi.ingress.tls.certificateSecretName }}
  {{- end }}
{{- end }}
