apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.consumerapi.name }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ .Values.consumerapi.name }}
  {{- if eq .Values.global.provider "GoogleCloud" }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.consumerapi.name }}"}'
  {{- end }}
  {{- if eq .Values.consumerapi.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.consumerapi.service.loadBalancer.azureResourceGroup }}
  {{- end }}
spec:
  type: {{ .Values.consumerapi.service.type }}
  {{- if eq .Values.consumerapi.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.consumerapi.service.loadBalancer.ip }}
  {{- end }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.consumerapi.name }}
