name: admin_api_types
description: The types used by the Admin API.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
