synthetic-package: false
arb-dir: lib/l10n
output-dir: lib/generated/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
preferred-supported-locales: [en]
use-escaping: false
