apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.admincli.name }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ .Values.admincli.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.admincli.name }}
  template:
    metadata:
      {{- with .Values.admincli.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.admincli.name }}
    spec:
      {{- with .Values.global.serviceAccount.name}}
      serviceAccountName: {{ . }}
      {{- end }}
      {{- with .Values.admincli.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admincli.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: settings-override
          configMap:
            name: configuration
      containers:
        - name: {{ .Values.admincli.name }}
          {{- with .Values.admincli.securityContext }}
          securityContext:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          resources:
            {{- toYaml .Values.admincli.resources | nindent 12 }}
          image: "{{ .Values.admincli.image.repository }}:{{- default .Chart.AppVersion .Values.admincli.image.tagOverride }}"
          imagePullPolicy: {{ .Values.admincli.image.pullPolicy }}
          volumeMounts:
            - name: settings-override
              mountPath: /app/appsettings.override.json
              subPath: appsettings.override.json
              readOnly: true
          env:
            {{- if .Values.global.useBuiltInEventbus }}
            - name: infrastructure__eventBus__vendor
              value: RabbitMQ
            - name: infrastructure__eventBus__rabbitMqEnableSsl
              value: "false"
            - name: infrastructure__eventBus__connectionInfo
              value: "rabbitmq"
            - name: infrastructure__eventBus__rabbitMQUsername
              value: "admin"
            - name: infrastructure__eventBus__rabbitMQPassword
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-password
                  key: "VALUE" 
            {{- end }}
            {{- include "generateEnvVars" (list .Values.global.env .Values.consumerapi.env) | nindent 12 }}
          tty: true
          command:
            - /bin/bash
      {{- with .Values.admincli.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admincli.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admincli.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
