apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.admincli.name }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ .Values.admincli.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.admincli.name }}
  template:
    metadata:
      {{- with .Values.admincli.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.admincli.name }}
    spec:
      {{- with .Values.global.serviceAccount.name}}
      serviceAccountName: {{ . }}
      {{- end }}
      {{- with .Values.admincli.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admincli.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.admincli.name }}
          {{- with .Values.admincli.securityContext }}
          securityContext:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          resources:
            {{- toYaml .Values.admincli.resources | nindent 12 }}
          image: "{{ .Values.admincli.image.repository }}:{{- default .Chart.AppVersion .Values.admincli.image.tagOverride }}"
          imagePullPolicy: {{ .Values.admincli.image.pullPolicy }}
          env:
            - name: Database__Provider
              value: {{ .Values.global.configuration.modules.devices.infrastructure.sqlDatabase.provider }}
            
            {{- $arg0 := default (list) (.Values.global.env) }}
            {{- $arg1 := default (list) (.Values.admincli.env) }}
            {{- $globalEnvMap := include "listToMap" $arg0 | fromYaml }}
            {{- $adminuiEnvMap := include "listToMap" $arg1 | fromYaml }}
            {{- $mergedEnvMap := merge $adminuiEnvMap $globalEnvMap }}
            {{- $mergedEnvList := include "mapToList" $mergedEnvMap }}
            {{- range $item := $mergedEnvMap }}
            - name: {{ $item.name }}
            {{- if $item.value }}
              value: {{ $item.value }}
            {{- else if $item.valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ $item.valueFrom.secretKeyRef.name }}
                  key: {{ $item.valueFrom.secretKeyRef.key }}
            {{- end }}
            {{- end }}            
          tty: true
          command:
            - /bin/bash
      {{- with .Values.admincli.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admincli.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admincli.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
