<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DocumentationFile></DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\BuildingBlocks\src\BuildingBlocks.Application.Abstractions\BuildingBlocks.Application.Abstractions.csproj" />
        <ProjectReference Include="..\..\..\..\BuildingBlocks\src\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
        <ProjectReference Include="..\..\..\Devices\src\Devices.Contracts\Devices.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Files\src\Files.Contracts\Files.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Messages\src\Messages.Contracts\Messages.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Relationships\src\Relationships.Contracts\Relationships.Contracts.csproj" />
        <ProjectReference Include="..\..\..\Tokens\src\Tokens.Contracts\Tokens.Contracts.csproj" />
        <ProjectReference Include="..\Synchronization.Domain\Synchronization.Domain.csproj" />
    </ItemGroup>
</Project>
