apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.consumerApi.name }}
  labels:
    {{- include "backbone.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.consumerApi.httpRoute.parentRefName }}
      namespace: {{ .Values.consumerApi.httpRoute.parentRefNamespace }}
  {{- with .Values.consumerApi.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.consumerApi.name }}
          port: 80
