using MediatR;

namespace Backbone.Modules.Relationships.Module.Features.PublicRelationshipTemplateReferences.ListPublicRelationshipTemplateReferences;

public class ListPublicRelationshipTemplateReferencesQuery : IRequest<IEnumerable<PublicRelationshipTemplateReferenceDefinition>>;
