name: admin_api_sdk
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  admin_api_types: ^1.0.0
  dio: ^5.5.0+1
  json_annotation: ^4.9.0
  meta: any

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
