name: admin_api_sdk
version: 1.0.0

environment:
  sdk: "^3.9.0"

resolution: workspace

dependencies:
  admin_api_types: ^1.0.0
  dio: ^5.7.0
  meta: any

dev_dependencies:
  very_good_analysis: ^10.0.0
