using OpenIddict.EntityFrameworkCore.Models;

namespace Backbone.Modules.Devices.Domain.OpenIddict;
public class CustomOpenIddictEntityFrameworkCoreAuthorization : OpenIddictEntityFrameworkCoreAuthorization<string, CustomOpenIddictEntityFrameworkCoreApplication, CustomOpenIddictEntityFrameworkCoreToken>
{
}
