using Backbone.Modules.Relationships.Application.Relationships.DTOs;

namespace Backbone.Modules.Relationships.Application.Relationships.Commands.RejectRelationshipChangeRequest;

public class RejectRelationshipChangeRequestResponse : RelationshipMetadataDTO;
