apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminui.name }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ .Values.adminui.name }}
  {{- if eq .Values.global.provider "GoogleCloud" }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.adminui.name }}"}'
  {{- end }}
spec:
  type: {{ .Values.adminui.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.adminui.name }}
