include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    sort_constructors_first: false
    public_member_api_docs: false
    always_use_package_imports: false
    avoid_setters_without_getters: false

formatter:
  page_width: 150
