// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Backbone.Quotas.Domain.Aggregates.Identities;
using Backbone.Quotas.Domain.Aggregates.Tiers;
using Backbone.Quotas.Infrastructure.Persistence.Database.ValueConverters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Backbone.Modules.Quotas.Infrastructure.CompiledModels.Postgres
{
    internal partial class TierQuotaEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType? baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Backbone.Modules.Quotas.Domain.Aggregates.Identities.TierQuota",
                typeof(TierQuota),
                baseEntityType);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(QuotaId),
                propertyInfo: typeof(Quota).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Quota).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 20,
                unicode: false,
                valueConverter: new QuotaIdEntityFrameworkValueConverter());
            id.AddAnnotation("Relational:IsFixedLength", true);

            var applyTo = runtimeEntityType.AddProperty(
                "ApplyTo",
                typeof(string),
                propertyInfo: typeof(Quota).GetProperty("ApplyTo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Quota).GetField("<ApplyTo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var _definitionId = runtimeEntityType.AddProperty(
                "_definitionId",
                typeof(TierQuotaDefinitionId),
                nullable: true,
                maxLength: 20,
                unicode: false,
                valueConverter: new TierQuotaDefinitionIdEntityFrameworkValueConverter());
            _definitionId.AddAnnotation("Relational:ColumnName", "DefinitionId");
            _definitionId.AddAnnotation("Relational:IsFixedLength", true);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { applyTo });

            var index0 = runtimeEntityType.AddIndex(
                new[] { _definitionId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ApplyTo")! },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Address")! })!,
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var tierQuotas = principalEntityType.AddNavigation("TierQuotas",
                runtimeForeignKey,
                onDependent: false,
                typeof(IReadOnlyCollection<TierQuota>),
                propertyInfo: typeof(Identity).GetProperty("TierQuotas", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Identity).GetField("_tierQuotas", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("_definitionId")! },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id")! })!,
                principalEntityType);

            var _definition = declaringEntityType.AddNavigation("_definition",
                runtimeForeignKey,
                onDependent: true,
                typeof(TierQuotaDefinition),
                fieldInfo: typeof(TierQuota).GetField("_definition", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "TierQuotas");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
