apiVersion: v1
kind: Service
metadata:
  name: {{ include "global.name" . }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ include "global.name" . }}
  {{- if eq .Values.global.provider "GoogleCloud" }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "global.name" . }}"}'
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.service.loadBalancer.azureResourceGroup }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancer.ip }}
  {{- end }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ include "global.name" . }}
