{{- if eq .Values.global.provider "Azure" }}
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Values.sseserver.name }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.sseserver.name }}
  default:
    interval: {{ .Values.sseserver.healthCheckPolicy.interval }}
    timeout: {{ .Values.sseserver.healthCheckPolicy.timeout }}
    healthyThreshold: {{ .Values.sseserver.healthCheckPolicy.healthyThreshold }}
    unhealthyThreshold: {{ .Values.sseserver.healthCheckPolicy.unhealthyThreshold }}
    http:
      host: {{ default .Values.global.hostname .Values.sseserver.healthCheckPolicy.hostOverride }}
      path: /health
      match:
        statusCodes:
          - start: 200
            end: 200
