{{- if eq ((((.Values.global.configuration.modules.devices.infrastructure).pushNotifications).providers).sse).enabled true }}
{{- if .Values.sseserver.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.sseserver.name }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.sseserver.httpRoute.parentRefName }}
      namespace: {{ .Values.sseserver.httpRoute.parentRefNamespace }}
      sectionName: {{ .Values.sseserver.httpRoute.parentRefSectionName }}
  {{- with .Values.sseserver.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/sse
      backendRefs:
        - name: {{ .Values.sseserver.name }}
          port: 8080
{{- end }}
{{- end }}
