apiVersion: v1
kind: Service
metadata:
  name: {{ include "global.name" . }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    app: {{ include "global.name" . }}
  {{- if eq .Values.global.provider "GoogleCloud" }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "global.name" . }}"}'
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ include "global.name" . }}
