apiVersion: v2
name: backbone
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

dependencies:
  - name: admincli
    version: "1.0.0"
    repository: file://charts/admincli
  - name: consumerapi
    version: "1.0.0"
    repository: file://charts/consumerapi
