apiVersion: v2
name: backbone-helm-chart
description: A Helm chart for Kubernetes
type: application

version: "<chartVersion>"

dependencies:
  - name: admincli
    version: "1.0.0"
    repository: file://charts/admincli
  - name: adminapi
    version: "1.0.0"
    repository: file://charts/adminapi
  - name: adminui
    version: "1.0.0"
    repository: file://charts/adminui
  - name: consumerapi
    version: "1.0.0"
    repository: file://charts/consumerapi

icon: https://raw.githubusercontent.com/nmshd/nmshd.github.io/main/assets/images/Logo.svg
home: https://enmeshed.eu
sources:
  - "https://github.com/nmshd/backbone"
