nameOverride: ""

# environment - possible values: "Development"/"Production"
environment: Production

# provider - possible values: "Azure"/"GoogleCloud"
provider: GoogleCloud

serviceAccount:
  create: true
  # name - defaults to the name of the chart
  name: ""
  annotations: {}

consumerApi:
  name: consumer-api
  replicas: 1

  image:
    repository: ghcr.io/nmshd/backbone-consumer-api
    tag: v0.0.12
    imagePullSecrets: []

  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  podSecurityContext:
    fsGroup: 2000

  podAnnotations: {}

  service:
    type: ClusterIP
    port: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: ""

  httpRoute:
    # parentRefName - the name of the gateway this Route wants to be attached to
    parentRefName: ""
    # parentRefNamespace - # the namespace of the gateway this Route wants to be attached to
    parentRefNamespace: ""
    hostnames: []

  # backendConfig - only applicable for Google Cloud
  backendConfig:
    healthCheck:
      checkIntervalSec: 15
      timeoutSec: 15
      healthyThreshold: 1
      unhealthyThreshold: 2

adminCli:
  name: admin-cli

  image:
    repository: ghcr.io/nmshd/backbone-admin-cli
    tag: v1.0.0
    imagePullSecrets: []

  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  podSecurityContext:
    fsGroup: 2000

  podAnnotations: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

rabbitmq:
  # create - if a RabbitMQ service should be created, set this to true; if you want to use an existing one, set it to false
  create: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # ingress:
  #   enabled: false
  #   className: ""
  #   annotations:
  #     {}
  #     # kubernetes.io/ingress.class: nginx
  #     # kubernetes.io/tls-acme: "true"
  #   hosts:
  #     - host: chart-example.local
  #       paths:
  #         - path: /
  #           pathType: ImplementationSpecific
  #   tls: []
  #   #  - secretName: chart-example-tls
  #   #    hosts:
  #   #      - chart-example.local

secrets:
  - name: challenges-sql-connectionstring
    value: "1" # a Kubernetes secret will be created for this
  - name: devices-sql-connectionstring
    value: "2"
  - name: files-sql-connectionstring
    value: "3"
  - name: messages-sql-connectionstring
    value: "4"
  - name: relationships-sql-connectionstring
    value: 5"
  - name: synchronization-sql-connectionstring
    value: "6"
  - name: tokens-sql-connectionstring
    value: "7"

  - name: devices-notificationhub-connectionstring
    value: "8"
  - name: jwt-signing-certificate
    value: "9"

configuration:
  Authentication:
    JwtLifetimeInSeconds: 300
    # JwtSigningCertificateSource - possible values: "config"/"file"
    JwtSigningCertificateSource: config
    # JwtSigningCertificateFile - only applicable if JwtSigningCertificateSource is "config"; should be set via Kubernetes secret
    JwtSigningCertificate: ""
  Cors:
    # AllowedOrigins - a semicolon-separated list of origins that are allowed to access the API; if empty, no origin is allowed
    AllowedOrigins: ""
    # AllowedMethods - a semicolon-separated list of headers that are exposed to the client; the specified headers are recommended, because they are used by the official Enmeshed app
    ExposedHeaders: X-Request-Time;X-Response-Time;X-Response-Duration-ms;X-Trace-Id
  SwaggerUi:
    # TokenUrl - the URL from which the Swagger UI can obtain a JWT; it usually follows the pattern "<backbone-base-url>/connect/token"
    TokenUrl: ""
  Infrastructure:
    EventBus:
      # Vendor - possible values: "RabbitMQ"/"Azure"/"GoogleCloud"
      Vendor: RabbitMQ
      # ConnectionInfo - the host name of the RabbitMQ service if Vendor is "RabbitMQ"; the connection string of the Azure Service Bus if Vendor is "Azure"; if Vendor is "GoogleCloud" this is not used
      ConnectionInfo: rabbitmq
      SubscriptionClientName: Backbone
      # RabbitMQUsername - only applicable if Vendor is "RabbitMQ"; should be set via Kubernetes secret
      RabbitMQUsername: admin
      # RabbitMQPassword - only applicable if Vendor is "RabbitMQ"; should be set via Kubernetes secret
      RabbitMQPassword: ""
      # ConnectionRetryCount - only applicable if Vendor is "RabbitMQ"; specifies how often the consumer API should retry to connect to the RabbitMQ service
      ConnectionRetryCount: 5
      # GcpPubSubProjectId - only applicable if Vendor is "GoogleCloud"; the ID of the Google Cloud project the Pub/Sub service is running in
      GcpPubSubProjectId: ""
      # GcpPubSubTopicName - only applicable if Vendor is "GoogleCloud"; the name of the Pub/Sub topic the consumer API should publish events to
      GcpPubSubTopicName: ""
  Modules:
    Challenges:
      Infrastructure:
        SqlDatabase:
          # Provider - possible values: "Postgres"/"SqlServer"
          Provider: ""
          # ConnectionString - should be set via Kubernetes secret
          ConnectionString: ""
    Devices:
      Application:
        # AddressPrefix - the prefix that should be used when generating Identity Addresses; the official Enmeshed App currently only supports "id1"
        AddressPrefix: id1
        # Pagination - the following options describe the default and maximum page size for the different endpoints
        Pagination:
          DefaultPageSize: 50
          MaxPageSize: 200
      Infrastructure:
        SqlDatabase:
          # Provider - possible values: "Postgres"/"SqlServer"
          Provider: ""
          # ConnectionString - should be set via Kubernetes secret
          ConnectionString: ""
        AzureNotificationHub:
          HubName: ""
    Files:
      Application:
        # Pagination - the following options describe the default and maximum page size for the different endpoints
        Pagination:
          DefaultPageSize: 50
          MaxPageSize: 200
      Infrastructure:
        SqlDatabase:
          # Provider - possible values: "Postgres"/"SqlServer"
          Provider: ""
          # ConnectionString - should be set via Kubernetes secret
          ConnectionString: ""
        BlobStorage:
          # CloudProvider - possible values: "GoogleCloud"/"Azure"
          CloudProvider: ""
          # ConnectionInfo - should be set via Kubernetes secret
          ConnectionInfo: ""
          # ContainerName - the name of the Bucket if CloudProvider=GoogleCloud; the name of the Container if CloudProvider=Azure
          ContainerName: ""
    Messages:
      Application:
        # MaxNumberOfUnreceivedMessagesFromOneSender - if this number is exceeded, the consumer API will not accept any more messages from the sender to the recipient in order to prevent spam
        MaxNumberOfUnreceivedMessagesFromOneSender: 20
        # Pagination - the following options describe the default and maximum page size for the different endpoints
        Pagination:
          DefaultPageSize: 50
          MaxPageSize: 200
      Infrastructure:
        SqlDatabase:
          # Provider - possible values: "Postgres"/"SqlServer"
          Provider: ""
          # ConnectionString - should be set via Kubernetes secret
          ConnectionString: ""
        BlobStorage:
          # CloudProvider - possible values: "GoogleCloud"/"Azure"
          CloudProvider: ""
          # ConnectionInfo - should be set via Kubernetes secret
          ConnectionInfo: ""
          # ContainerName - the name of the Bucket if CloudProvider=GoogleCloud; the name of the Container if CloudProvider=Azure
          ContainerName: ""
    Relationships:
      Application:
        # Pagination - the following options describe the default and maximum page size for the different endpoints
        Pagination:
          DefaultPageSize: 50
          MaxPageSize: 200
      Infrastructure:
        SqlDatabase:
          # Provider - possible values: "Postgres"/"SqlServer"
          Provider: ""
          # ConnectionString - should be set via Kubernetes secret
          ConnectionString: ""
        BlobStorage:
          # CloudProvider - possible values: "GoogleCloud"/"Azure"
          CloudProvider: ""
          # ConnectionInfo - should be set via Kubernetes secret
          ConnectionInfo: ""
          # ContainerName - the name of the Bucket if CloudProvider=GoogleCloud; the name of the Container if CloudProvider=Azure
          ContainerName: ""
    Synchronization:
      Application:
        # Pagination - the following options describe the default and maximum page size for the different endpoints
        Pagination:
          DefaultPageSize: 50
          MaxPageSize: 200
      Infrastructure:
        SqlDatabase:
          # Provider - possible values: "Postgres"/"SqlServer"
          Provider: ""
          # ConnectionString - should be set via Kubernetes secret
          ConnectionString: ""
        BlobStorage:
          # CloudProvider - possible values: "GoogleCloud"/"Azure"
          CloudProvider: ""
          # ConnectionInfo - should be set via Kubernetes secret
          ConnectionInfo: ""
          # ContainerName - the name of the Bucket if CloudProvider=GoogleCloud; the name of the Container if CloudProvider=Azure
          ContainerName: ""
    Tokens:
      Application:
        # Pagination - the following options describe the default and maximum page size for the different endpoints
        Pagination:
          DefaultPageSize: 50
          MaxPageSize: 200
      Infrastructure:
        SqlDatabase:
          # Provider - possible values: "Postgres"/"SqlServer"
          Provider: ""
          # ConnectionString - should be set via Kubernetes secret
          ConnectionString: ""
        BlobStorage:
          # CloudProvider - possible values: "GoogleCloud"/"Azure"
          CloudProvider: ""
          # ConnectionInfo - should be set via Kubernetes secret
          ConnectionInfo: ""
          # ContainerName - the name of the Bucket if CloudProvider=GoogleCloud; the name of the Container if CloudProvider=Azure
          ContainerName: ""
