{{- if .Values.global.useBuiltInEventbus }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-password
  labels:
    {{- include "global.labels" $ | nindent 4 }}
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rabbitmq-password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $rabbitmqPassword to existing secret data or generate a random one when not exists
  {{- $rabbitmqPassword := (get $secretData "VALUE") | default (randAlphaNum 32 | b64enc) }}
  VALUE: {{ $rabbitmqPassword | quote }}
{{- end }}
