FROM mcr.microsoft.com/dotnet/sdk:8.0

EXPOSE 80

WORKDIR /app

ENV ASPNETCORE_URLS=http://0.0.0.0:8080

ENTRYPOINT ["dotnet", "watch", "--non-interactive", "--project", "ConsumerApi/ConsumerApi.csproj"]
