name: Check Pull Request

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  merge_group:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  validate-pr-label:
    name: Validate the Pull Request's labels
    runs-on: ubuntu-latest
    steps:
      - name: PR must be labeled
        uses: js-soft/github-actions/validate-pr-label@7341f0fefe5319a41ead6e19d833f142a306159a # main
