name: Publish Helm Chart

on:
  push:
    tags:
      - "helm/*"

jobs:
  publish-helm-chart:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install script dependencies
        run: npm install --prefix ./.ci
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version from git tag
        id: extract-version-from-git-tag
        run: echo "VERSION=$(./.ci/extractVersionFromGitTag.ts)" >> $GITHUB_OUTPUT
        env:
          GIT_TAG: ${{ github.ref_name }}
      - name: Build Helm Chart
        run: ./.ci/helm/buildChart.ts
        env:
          VERSION: ${{ steps.extract-version-from-git-tag.outputs.VERSION }}
      - name: Push Helm Chart
        run: ./.ci/helm/pushChart.ts
        env:
          VERSION: ${{ steps.extract-version-from-git-tag.outputs.VERSION }}
