name: Publish Helm Chart

on:
  push:
    tags:
      - "helm/*"

jobs:
  publish-helm-chart:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install script dependencies
        run: npm install --prefix ./.ci
      - run: echo "$PASSWORD" | helm registry login -u $USER --password-stdin https://ghcr.io
        env:
          USER: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version from git tag
        id: extract-version-from-git-tag
        run: echo "VERSION=$(./.ci/extractVersionFromGitTag.js)" >> $GITHUB_OUTPUT
        env:
          GIT_TAG: ${{ github.ref_name }}
      - name: Build Helm Chart
        run: ./.ci/helm/buildChart.js
        env:
          VERSION: ${{ steps.extract-version-from-git-tag.outputs.VERSION }}
      - name: Push Helm Chart
        run: ./.ci/helm/pushChart.js
        env:
          VERSION: ${{ steps.extract-version-from-git-tag.outputs.VERSION }}
