name: Weekly Release of Dependency Updates

on:
  schedule:
    - cron: "0 2 * * 2" # every Tuesday at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: weekly-dependency-release
  cancel-in-progress: false

jobs:
  release:
    uses: js-soft/github-actions/.github/workflows/release-dependency-updates.yml@main
    secrets:
      github-token: ${{ secrets.GH_PAT }}
