name: admin_ui
description: "The Enmeshed Backbone Admin UI."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  web:
    generate: true
