using MediatR;

namespace Backbone.Modules.Devices.Application.Identities.Commands.CancelStaleIdentityDeletionProcesses;
public class CancelStaleIdentityDeletionProcessesCommand : IRequest<CancelStaleIdentityDeletionProcessesResponse>;
